services:
  tg-service:
    build: ./
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8000:8000
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5433:5432"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - db